#!/bin/bash
dos2unix /etc/rc.local
update-rc.d -f minidlna remove
update-rc.d -f upmpdcli remove
(echo root; echo root) | smbpasswd -a -s root
sudo bash /sbin/delllogs
sudo bash /sbin/fixupd
sudo bash /sbin/alsaupdate
sed -i 's/disp.screen0_output_mode=1920x1080p60/monitor=none net.ifnames=0 biosdevname=0/' /boot/boot.cmd
mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr 
sed -i 's/-e//' /etc/rc.local
swapoff -a
exit 0
