#! /bin/sh
print "Content-Type: text/html\n\n";
mpc clear
mpc stop;systemctl stop mpd.socket;killall -s 9 mpd;/etc/init.d/mpd stop
sudo umount -f /mnt/NAS/*
sudo umount -l /mnt/NAS/*
sudo rm -r /mnt/NAS*
sudo rm -r /var/lib/mpd/music/NAS*
mv /var/www/db/player.db /var/www/db/bkp.db
cp /var/www/db/bkp.db /var/www/db/player.db
chmod 777 /var/www/db/player.db
sqlite3 /var/www/db/player.db 'delete from cfg_source'
sudo mkdir /mnt/NAS
sudo chmod -R 777 /mnt/NAS
cd /var/lib/mpd/music/
sudo ln -s /mnt/NAS /var/lib/mpd/music/NAS
sudo chmod -R 777 /var/lib/mpd/music
service mpd start;/etc/init.d/mpd start
sleep 2
mpc update NAS
exit 0
