#!/bin/bash
ver="$(uname -r  | sed -e 's/[^0-9]//g')"  # get kernel release version
latestver="41816"
echo "$b"
if [ "$ver" != "$latestver" ];
then
echo "Нужно обновить ядро!"
curl -o http://digitall.in.ua/vamp/linux-image-dev-sunxi_5.65_armhf.deb
curl -o http://digitall.in.ua/vamp/linux-dtb-dev-sunxi_5.65_armhf.deb
curl -o http://digitall.in.ua/vamp/linux-headers-dev-sunxi_5.65_armhf.deb
dpkg -i linux-image-dev-sunxi_5.65_armhf.deb linux-dtb-dev-sunxi_5.65_armhf.deb linux-headers-dev-sunxi_5.65_armhf.de && apt-get purge -y linux-headers-4.4* linux-image-4.4* linux-headers-4.6* linux-image-4.6* linux-headers-4.17* linux-image-4.17*  linux-headers-4.18.14 linux-image-4.18.14
else 
echo "Уже используеться последняя версия ядра linux!"
fi
echo "Finished"
exit 0
