#! /bin/sh
mpdver="$(mpd -V | grep Music | cut -d "0" -f 2,3)" 
mpdver="${mpdver%.*-*}"        # remove suffix starting with '.' and containing '-'
mpdver="${mpdver//.}"          # remove periods (a single `/` would do here)
newver="2015"
if [ "$mpdver" -ne "$newver" ];
then
echo "Обновление MPD"
cd /root/
wget http://digitall.in.ua/mpd.tar.bz2
mkdir ./mpd
tar -xjvf mpd.tar.bz2 -C ./mpd
cd ./mpd
make install&&bash /sbin/update-mpd-final
rm -R /root/*mpd*
fi
echo "Версия MPD не нуждается в обновлении"
rm -R /root/*mpd*
